language: "en"

pipeline:
  - name: "nlp_spacy"
    model: "en"
  - name: "tokenizer_spacy"
  - name: "intent_featurizer_spacy"
  - name: "intent_classifier_sklearn"
  - name: "ner_duckling"
    dimensions: ["email"]
